org: joaofernandesdev

service: gamevault-api
frameworkVersion: "4"

plugins:
  - serverless-offline

provider:
  name: aws
  region: "us-east-1"
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    TWITCH_CLIENT_ID: ${env:TWITCH_CLIENT_ID}
    TWITCH_CLIENT_SECRET: ${env:TWITCH_CLIENT_SECRET}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - "arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*:*:*"

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false
    external:
      - bcryptjs
      - jsonwebtoken
      - axios
      - "@neondatabase/serverless"

functions:
  signUp:
    handler: src/functions/auth/signUp.handler
    events:
      - httpApi:
          path: /signup
          method: post

  signIn:
    handler: src/functions/auth/signIn.handler
    events:
      - httpApi:
          path: /signin
          method: post

  getProfile:
    handler: src/functions/auth/getProfile.handler
    events:
      - httpApi:
          path: /profile
          method: get

  createGame:
    handler: src/functions/addGame.handler
    events:
      - httpApi:
          path: /games
          method: post

  updateGameById:
    handler: src/functions/updateGameById.handler
    events:
      - httpApi:
          path: /games/{gameId}
          method: put

  listGames:
    handler: src/functions/listGames.handler
    events:
      - httpApi:
          path: /games
          method: get

  getGameById:
    handler: src/functions/getGameById.handler
    events:
      - httpApi:
          path: /games/{gameId}
          method: get

  deleteGameById:
    handler: src/functions/deleteGameById.handler
    events:
      - httpApi:
          path: /games/{gameId}
          method: delete

  searchGame:
    handler: src/functions/searchGame.handler
    events:
      - httpApi:
          path: /search
          method: get
