org: joaofernandesdev

service: gamevault-api
frameworkVersion: "4"

plugins:
  - serverless-offline

provider:
  name: aws
  region: "us-east-1"
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - "arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*:*:*"

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false
    external:
      - bcryptjs
      - jsonwebtoken
      - "@neondatabase/serverless"

functions:
  signUp:
    handler: src/functions/auth/signUp.handler
    events:
      - http:
          path: /signup
          method: post
  signIn:
    handler: src/functions/auth/signIn.handler
    events:
      - http:
          path: /signin
          method: post

  createGame:
    handler: src/functions/addGame.handler
    events:
      - http:
          path: /games
          method: post

  updateGameById:
    handler: src/functions/updateGameById.handler
    events:
      - http:
          path: /games/{gameId}
          method: put

  listGames:
    handler: src/functions/listGames.handler
    events:
      - http:
          path: /games
          method: get

  getGameById:
    handler: src/functions/getGameById.handler
    events:
      - http:
          path: /games/{gameId}
          method: get
