org: joaofernandesdev

service: gamevault-api
frameworkVersion: "4"

plugins:
  - serverless-offline

provider:
  name: aws
  region: "us-east-1"
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource:
            - "arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*:*:*"

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false
    external:
      - bcryptjs
      - jsonwebtoken
      - '@neondatabase/serverless'

functions:
  signUp:
    handler: src/functions/auth/signUp.handler
    events:
      - http:
          path: /users
          method: post

  createGame:
    handler: src/functions/addGame.handler
    events:
      - http:
          path: /games
          method: post
